In [88]:
import pandas as pd

In [89]:
df=pd.read_csv("general_data.csv")

In [90]:
df.head(2)

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   51        No      Travel_Rarely                   Sales                 6   
1   31       Yes  Travel_Frequently  Research & Development                10   

   Education EducationField  EmployeeCount  EmployeeID  Gender  ...  \
0          2  Life Sciences              1           1  Female  ...   
1          1  Life Sciences              1           2  Female  ...   

   NumCompaniesWorked Over18 PercentSalaryHike  StandardHours  \
0                 1.0      Y                11              8   
1                 0.0      Y                23              8   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear  YearsAtCompany  \
0                 0               1.0                      6               1   
1                 1               6.0                      3               5   

   YearsSinceLastPromotion  YearsWithCurrManager  
0                        0                     0  
1                        1                     4  

[2 rows x 24 columns]

In [91]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'Department', 'DistanceFromHome',
       'Education', 'EducationField', 'EmployeeCount', 'EmployeeID', 'Gender',
       'JobLevel', 'JobRole', 'MaritalStatus', 'MonthlyIncome',
       'NumCompaniesWorked', 'Over18', 'PercentSalaryHike', 'StandardHours',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'YearsAtCompany', 'YearsSinceLastPromotion', 'YearsWithCurrManager'],
      dtype='object')

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4410 entries, 0 to 4409
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Age                      4410 non-null   int64  
 1   Attrition                4410 non-null   object 
 2   BusinessTravel           4410 non-null   object 
 3   Department               4410 non-null   object 
 4   DistanceFromHome         4410 non-null   int64  
 5   Education                4410 non-null   int64  
 6   EducationField           4410 non-null   object 
 7   EmployeeCount            4410 non-null   int64  
 8   EmployeeID               4410 non-null   int64  
 9   Gender                   4410 non-null   object 
 10  JobLevel                 4410 non-null   int64  
 11  JobRole                  4410 non-null   object 
 12  MaritalStatus            4410 non-null   object 
 13  MonthlyIncome            4410 non-null   int64  
 14  NumCompaniesWorked      

In [93]:
'''interpolating the null values'''
df.TotalWorkingYears=df.TotalWorkingYears.interpolate()
df.NumCompaniesWorked=df.NumCompaniesWorked.interpolate()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4410 entries, 0 to 4409
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Age                      4410 non-null   int64  
 1   Attrition                4410 non-null   object 
 2   BusinessTravel           4410 non-null   object 
 3   Department               4410 non-null   object 
 4   DistanceFromHome         4410 non-null   int64  
 5   Education                4410 non-null   int64  
 6   EducationField           4410 non-null   object 
 7   EmployeeCount            4410 non-null   int64  
 8   EmployeeID               4410 non-null   int64  
 9   Gender                   4410 non-null   object 
 10  JobLevel                 4410 non-null   int64  
 11  JobRole                  4410 non-null   object 
 12  MaritalStatus            4410 non-null   object 
 13  MonthlyIncome            4410 non-null   int64  
 14  NumCompaniesWorked      

In [94]:
df1=df.drop(columns="EmployeeID")


In [95]:
df2=df1.drop(columns="Over18")
df2.head(2)

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   51        No      Travel_Rarely                   Sales                 6   
1   31       Yes  Travel_Frequently  Research & Development                10   

   Education EducationField  EmployeeCount  Gender  JobLevel  ...  \
0          2  Life Sciences              1  Female         1  ...   
1          1  Life Sciences              1  Female         1  ...   

  MonthlyIncome NumCompaniesWorked  PercentSalaryHike  StandardHours  \
0        131160                1.0                 11              8   
1         41890                0.0                 23              8   

   StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  YearsAtCompany  \
0                 0                1.0                      6               1   
1                 1                6.0                      3               5   

   YearsSinceLastPromotion  YearsWithCurrManager  
0                        0                     0  
1                        1                     4  

[2 rows x 22 columns]

In [96]:
df2["Attrition"]=df2["Attrition"].map({"No":0, "Yes":1})

In [97]:
df2["Attrition"]

0       0
1       1
2       0
3       0
4       0
       ..
4405    0
4406    0
4407    0
4408    0
4409    0
Name: Attrition, Length: 4410, dtype: int64

In [98]:
df2.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'Department', 'DistanceFromHome',
       'Education', 'EducationField', 'EmployeeCount', 'Gender', 'JobLevel',
       'JobRole', 'MaritalStatus', 'MonthlyIncome', 'NumCompaniesWorked',
       'PercentSalaryHike', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'YearsAtCompany',
       'YearsSinceLastPromotion', 'YearsWithCurrManager'],
      dtype='object')

In [141]:
df2.describe().T

count          mean           std      min      25%  \
Age                      4410.0     36.923810      9.133301     18.0     30.0   
Attrition                4410.0      0.161224      0.367780      0.0      0.0   
BusinessTravel           4410.0      1.392517      0.665304      1.0      1.0   
Department               4410.0      1.739456      0.527673      1.0      1.0   
DistanceFromHome         4410.0      9.192517      8.105026      1.0      2.0   
Education                4410.0      2.912925      1.023933      1.0      2.0   
EducationField           4410.0      1.930612      1.019960      1.0      1.0   
EmployeeCount            4410.0      1.000000      0.000000      1.0      1.0   
Gender                   4410.0      0.600000      0.489954      0.0      0.0   
JobLevel                 4410.0      2.063946      1.106689      1.0      1.0   
JobRole                  4410.0      4.389116      2.439947      1.0      2.0   
MaritalStatus            4410.0      1.764626      0.790578      1.0      1.0   
MonthlyIncome            4410.0  65029.312925  47068.888559  10090.0  29110.0   
NumCompaniesWorked       4410.0      2.692517      2.495792      0.0      1.0   
PercentSalaryHike        4410.0     15.209524      3.659108     11.0     12.0   
StandardHours            4410.0      8.000000      0.000000      8.0      8.0   
StockOptionLevel         4410.0      0.793878      0.851883      0.0      0.0   
TotalWorkingYears        4410.0     11.280726      7.778918      0.0      6.0   
TrainingTimesLastYear    4410.0      2.799320      1.288978      0.0      2.0   
YearsAtCompany           4410.0      7.008163      6.125135      0.0      3.0   
YearsSinceLastPromotion  4410.0      2.187755      3.221699      0.0      0.0   
YearsWithCurrManager     4410.0      4.123129      3.567327      0.0      2.0   

                             50%      75%       max  
Age                         36.0     43.0      60.0  
Attrition                    0.0      0.0       1.0  
BusinessTravel               1.0      2.0       3.0  
Department                   2.0      2.0       3.0  
DistanceFromHome             7.0     14.0      29.0  
Education                    3.0      4.0       5.0  
EducationField               2.0      2.0       5.0  
EmployeeCount                1.0      1.0       1.0  
Gender                       1.0      1.0       1.0  
JobLevel                     2.0      3.0       5.0  
JobRole                      3.0      6.0       9.0  
MaritalStatus                2.0      2.0       3.0  
MonthlyIncome            49190.0  83800.0  199990.0  
NumCompaniesWorked           2.0      4.0       9.0  
PercentSalaryHike           14.0     18.0      25.0  
StandardHours                8.0      8.0       8.0  
StockOptionLevel             1.0      1.0       3.0  
TotalWorkingYears           10.0     15.0      40.0  
TrainingTimesLastYear        3.0      3.0       6.0  
YearsAtCompany               5.0      9.0      40.0  
YearsSinceLastPromotion      1.0      3.0      15.0  
YearsWithCurrManager         3.0      7.0      17.0

In [146]:
print(df2.shape)
print(df.shape)

(4410, 22)
(4410, 24)


In [99]:
df2["BusinessTravel"].unique()

array(['Travel_Rarely', 'Travel_Frequently', 'Non-Travel'], dtype=object)

In [100]:
df2["BusinessTravel"]=df2["BusinessTravel"].map({'Travel_Rarely':1, 'Travel_Frequently':2, 'Non-Travel':3})

In [101]:
df2["BusinessTravel"].unique()

array([1, 2, 3], dtype=int64)

In [102]:
df2["Department"].unique()


array(['Sales', 'Research & Development', 'Human Resources'], dtype=object)

In [103]:
df2["Department"]=df2["Department"].map({'Sales':1, 'Research & Development':2, 'Human Resources':3})

In [104]:
df2["Department"].unique()

array([1, 2, 3], dtype=int64)

In [105]:
df2['EducationField'].unique()

array(['Life Sciences', 'Other', 'Medical', 'Marketing',
       'Technical Degree', 'Human Resources'], dtype=object)

In [106]:
df2['EducationField']=df2['EducationField'].map({'Life Sciences':1, 'Other':2, 'Medical':2, 'Marketing':3,'Technical Degree':4, 'Human Resources':5})

In [107]:
df2['EducationField'].unique()

array([1, 2, 3, 4, 5], dtype=int64)

In [108]:
df2["Gender"].unique()

array(['Female', 'Male'], dtype=object)

In [109]:
df2['Gender']=df2['Gender'].map({'Female':0, 'Male':1})

In [110]:
df2["Gender"].unique()

array([0, 1], dtype=int64)

In [111]:
df2.head(2)

Age  Attrition  BusinessTravel  Department  DistanceFromHome  Education  \
0   51          0               1           1                 6          2   
1   31          1               2           2                10          1   

   EducationField  EmployeeCount  Gender  JobLevel  ... MonthlyIncome  \
0               1              1       0         1  ...        131160   
1               1              1       0         1  ...         41890   

  NumCompaniesWorked  PercentSalaryHike  StandardHours  StockOptionLevel  \
0                1.0                 11              8                 0   
1                0.0                 23              8                 1   

   TotalWorkingYears  TrainingTimesLastYear  YearsAtCompany  \
0                1.0                      6               1   
1                6.0                      3               5   

   YearsSinceLastPromotion  YearsWithCurrManager  
0                        0                     0  
1                        1                     4  

[2 rows x 22 columns]

In [112]:
df2["JobRole"].unique()

array(['Healthcare Representative', 'Research Scientist',
       'Sales Executive', 'Human Resources', 'Research Director',
       'Laboratory Technician', 'Manufacturing Director',
       'Sales Representative', 'Manager'], dtype=object)

In [113]:
df2['JobRole']=df2['JobRole'].map({'Healthcare Representative':1, 'Research Scientist':2, 'Sales Executive':3, 'Human Resources':4, 'Research Director':5,'Laboratory Technician':6, 'Manufacturing Director':7,'Sales Representative':8, 'Manager':9})

In [114]:
df2["JobRole"].unique()

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [115]:
df2['MaritalStatus']=df2['MaritalStatus'].map({'Married':1, 'Single':2, 'Divorced':3})

In [116]:
#Independent variable
x=df2[['Age', 'BusinessTravel', 'Department', 'DistanceFromHome',
       'Education', 'EducationField', 'EmployeeCount', 'Gender',
       'JobLevel', 'JobRole', 'MaritalStatus', 'MonthlyIncome',
       'NumCompaniesWorked', 'PercentSalaryHike', 'StandardHours',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'YearsAtCompany', 'YearsSinceLastPromotion', 'YearsWithCurrManager']]
y=df2['Attrition']

In [117]:
x["MaritalStatus"].unique()

array([1, 2, 3], dtype=int64)

In [122]:
import statsmodels.api as sm

In [123]:
x1=sm.add_constant(x)

In [124]:
logReg=sm.Logit(y,x1)

In [126]:
res=logReg.fit()
res.summary()

Optimization terminated successfully.
         Current function value: 0.404476
         Iterations 7


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:              Attrition   No. Observations:                 4410
Model:                          Logit   Df Residuals:                     4390
Method:                           MLE   Df Model:                           19
Date:                Sun, 09 Aug 2020   Pseudo R-squ.:                 0.08426
Time:                        12:04:06   Log-Likelihood:                -1783.7
converged:                       True   LL-Null:                       -1947.9
Covariance Type:            nonrobust   LLR p-value:                 3.105e-58
===========================================================================================
                              coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------
Age                        -0.0353      0.007     -5.198      0.000      -0.049      -0.022
BusinessTravel             -0.0052      0.065     -0.080      0.936      -0.132       0.122
Department                  0.2946      0.081      3.649      0.000       0.136       0.453
DistanceFromHome           -0.0024      0.005     -0.459      0.646      -0.013       0.008
Education                  -0.0509      0.042     -1.222      0.222      -0.132       0.031
EducationField           8.778e-05      0.041      0.002      0.998      -0.080       0.080
EmployeeCount               0.0030   9.86e+14   3.08e-18      1.000   -1.93e+15    1.93e+15
Gender                      0.0618      0.088      0.699      0.484      -0.111       0.235
JobLevel                   -0.0312      0.039     -0.809      0.419      -0.107       0.044
JobRole                    -0.0496      0.018     -2.807      0.005      -0.084      -0.015
MaritalStatus               0.0410      0.056      0.731      0.465      -0.069       0.151
MonthlyIncome           -2.283e-06   9.43e-07     -2.421      0.015   -4.13e-06   -4.35e-07
NumCompaniesWorked          0.1090      0.019      5.886      0.000       0.073       0.145
PercentSalaryHike           0.0141      0.012      1.213      0.225      -0.009       0.037
StandardHours               0.0243   1.23e+14   1.97e-16      1.000   -2.41e+14    2.41e+14
StockOptionLevel           -0.0598      0.042     -1.412      0.158      -0.143       0.023
TotalWorkingYears          -0.0562      0.006     -9.985      0.000      -0.067      -0.045
TrainingTimesLastYear      -0.1298      0.034     -3.806      0.000      -0.197      -0.063
YearsAtCompany              0.0042      0.016      0.266      0.790      -0.027       0.035
YearsSinceLastPromotion     0.1267      0.020      6.211      0.000       0.087       0.167
YearsWithCurrManager       -0.1342      0.030     -4.534      0.000      -0.192      -0.076
===========================================================================================
"""

# Inference

1. So out of all the Independent variables the only variables such as Age, Department,JobRole,MonthlyIncome, NumCompaniesWorked, TotalWorkingYears, TrainingTimesLastYear,YearsSinceLastPromotion, YearsWithCurrManager are significant because the P value is less than 0.05
2. And the variables Age, Department,JobRole, NumCompaniesWorked,TotalWorkingYears, TrainingTimesLastYear,YearsSinceLastPromotion, YearsWithCurrManager are the most significant variables for the consideration of Attrition

### checking the probability of Attrition Yes or No on the basis of new Data

In [136]:
import numpy as np
age=int(input("Enter the Age :--->"))
dept=int(input("Enter the Department as Sales:1, Research & Development:2, Human Resources:3----->"))
inc=int(input("Enter the monthly Income----->"))
JRole=int(input("Enter the Job Role of the employee as Healthcare Representative:1, Research Scientist:2, Sales Executive:3, Human Resources:4, Research Director:5,Laboratory Technician:6, Manufacturing Director:7,Sales Representative:8, Manager:9------>"))
Ncomp=int(input("Enter the number of companies the emoloyee worked as 0,1,2,3,4........,n------->"))
Exp=int(input("Enter Total working year of companies or the experience of the employee as integer------>"))
training=int(input("Enter the Number of times training was conducted for this employee last year as an integer------>"))
promot=int(input("Enter Number of years since last promotion as an integer----->"))
currMan=int(input("Enter the Number of years under current manager----------->"))
c=np.exp(0.0353*age-dept*0.2946	+inc*2.283e-06+JRole*0.0496-Ncomp*0.1090+Exp*0.0562+training*0.1298-promot*0.1267+currMan*0.1342)

Enter the Age :--->32
Enter the Department as Sales:1, Research & Development:2, Human Resources:3----->2
Enter the monthly Income----->10000
Enter the Job Role of the employee as Healthcare Representative:1, Research Scientist:2, Sales Executive:3, Human Resources:4, Research Director:5,Laboratory Technician:6, Manufacturing Director:7,Sales Representative:8, Manager:9------>3
Enter the number of companies the emoloyee worked as 0,1,2,3,4........,n------->2
Enter Total working year of companies or the experience of the employee as integer------>3
Enter the Number of times training was conducted for this employee last year as an integer------>3
Enter Number of years since last promotion as an integer----->2
Enter the Number of years under current manager----------->2


In [154]:
P=1/(1+c)
print("AGE:---->",age)
print("Department Sales:1, Research & Development:2, Human Resources:3----------->",dept)
print("Income:---->",inc)
print("Job Role Healthcare Representative:1, Research Scientist:2, Sales Executive:3, Human Resources:4, Research Director:5,Laboratory Technician:6, Manufacturing Director:7,Sales Representative:8, Manager:9:--->",JRole)
print("Number of copanies worked:------>",Ncomp)
print("Experience:-------->",Exp)
print("Training:-------->",training)
print("Promotion:-------->",promot)
print("Current Manager:-------->",currMan)
if P>0.5:
    print("So From the above entered data the probability of Atrrition is High")
else: 
    print("So From the above entered data the probability of Atrrition is Low")

AGE:----> 32
Department Sales:1, Research & Development:2, Human Resources:3-----------> 2
Income:----> 10000
Job Role Healthcare Representative:1, Research Scientist:2, Sales Executive:3, Human Resources:4, Research Director:5,Laboratory Technician:6, Manufacturing Director:7,Sales Representative:8, Manager:9:---> 3
Number of copanies worked:------> 2
Experience:--------> 3
Training:--------> 3
Promotion:--------> 2
Current Manager:--------> 2
So From the above entered data the probability of Atrrition is Low
