# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np

In [2]:
num=np.random.random((3,3,3))
num

array([[[0.31353782, 0.15292173, 0.58439378],
        [0.2844249 , 0.34153983, 0.51409491],
        [0.73250703, 0.10973579, 0.24485482]],

       [[0.66345514, 0.83783203, 0.08876264],
        [0.51904281, 0.93399028, 0.96030759],
        [0.05003068, 0.41277991, 0.12770234]],

       [[0.67908365, 0.16342666, 0.56802805],
        [0.9486614 , 0.22760121, 0.81006846],
        [0.22468993, 0.92585775, 0.74918731]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
import numpy as np

In [4]:
num1=np.diag([1,2,3,4,5])
print("\n The required Matrix is:\n",num1)


 The required Matrix is:
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


# 4. Normalize a 5x5 random matrix

In [5]:
print("Before Normalization\n")
num3=np.random.random((5,5))
print(num3)
print("MIN",num3.min())
print("Max",num3.max())
norm=(num3-num3.min())/(num3.max()-num3.min())
print(" ")
print("After Normalizing the array the values are")
print(norm)

Before Normalization

[[0.26678511 0.15489687 0.46263834 0.30711103 0.7523276 ]
 [0.77556127 0.56105596 0.62808404 0.06136215 0.4247275 ]
 [0.38979541 0.95460736 0.71709064 0.14989455 0.53340218]
 [0.74615533 0.9312091  0.48899836 0.60145976 0.5566881 ]
 [0.40680265 0.05837009 0.74379664 0.26147066 0.78078522]]
MIN 0.05837009085871203
Max 0.9546073588825439
 
After Normalizing the array the values are
[[0.23254447 0.10770225 0.45107279 0.27753917 0.77430111]
 [0.80022468 0.56088481 0.63567313 0.00333847 0.40877279]
 [0.3697964  1.         0.73498455 0.10212079 0.53002938]
 [0.76741423 0.97389279 0.48048467 0.60596639 0.55601126]
 [0.38877267 0.         0.76478247 0.22661473 0.80605344]]


# 5.  How to find common values between two arrays?

In [6]:
a1=np.array([1,2,3,4])
print(a1)
a2=np.array([4,31,23,22])
print(a2)
c=np.intersect1d(a1,a2,return_indices=False)
print("common values between two arrays is:",c)

[1 2 3 4]
[ 4 31 23 22]
common values between two arrays is: [4]


# 6.How to get the dates of yesterday, today and tomorrow?

In [7]:
import time
from datetime import date
t=date.today()
print("Today's date:",t)

Today's date: 2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [8]:
num4=np.random.random((2,2))
num5=np.random.random((2,2))
print("first random array",num4) 
print("Second random array",num5)
print("The two Random arrays are\n",num4,"\n",num5)
b=np.array_equal(num4,num5)
if b==False:
    print("Unequal")
else:
    printnt("equal")

first random array [[0.29565912 0.23965603]
 [0.25775453 0.54659429]]
Second random array [[0.78398553 0.0988621 ]
 [0.10278026 0.11343357]]
The two Random arrays are
 [[0.29565912 0.23965603]
 [0.25775453 0.54659429]] 
 [[0.78398553 0.0988621 ]
 [0.10278026 0.11343357]]
Unequal


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [9]:
num6=np.random.random(10)
print("Original Random Vector\n\n",num6)
m=num6.max()
print("The maximum Entry is:--->",m)
num6[num6.argmax()]=0
print("\nThe Maximum Entry replaced by zero is:")
print(num6)

Original Random Vector

 [2.66271132e-01 1.93512920e-01 7.92472745e-01 4.09084479e-01
 6.82299177e-01 1.57174339e-04 9.34814273e-01 5.91390179e-01
 4.26231845e-01 6.91682825e-01]
The maximum Entry is:---> 0.9348142732592812

The Maximum Entry replaced by zero is:
[2.66271132e-01 1.93512920e-01 7.92472745e-01 4.09084479e-01
 6.82299177e-01 1.57174339e-04 0.00000000e+00 5.91390179e-01
 4.26231845e-01 6.91682825e-01]


# 9. How to print all the values of an array?

In [10]:
num6=np.array([1,2,3,4])
print(num6)

[1 2 3 4]


# 10.Subtract the mean of each row of a matrix

In [11]:
num7=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(num7)
m=np.mean(num7)
print("The mean of the matrix is:-->",m)
num9=num7-m
print("Subtracting the mean of each row of a matrix is:-->\n",num9)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
The mean of the matrix is:--> 5.0
Subtracting the mean of each row of a matrix is:-->
 [[-4. -3. -2.]
 [-1.  0.  1.]
 [ 2.  3.  4.]]


# 12.How to get the diagonal of a dot product?

In [12]:
a3=[[52,22],[15,68]]
a4=[[69,12],[73,24]]
p=np.dot(a3,a4)
print(a3)
print(a4)
print("\nthe dot product is:--->",p)
print("\nThe diagonal of a dot product is:-->\n",np.diag(p))

[[52, 22], [15, 68]]
[[69, 12], [73, 24]]

the dot product is:---> [[5194 1152]
 [5999 1812]]

The diagonal of a dot product is:-->
 [5194 1812]


# 13.How to find the most frequent value in an array?

In [13]:
num10=np.array([1,2,3,4,10,6,2,7,0,8])
print("Entered values in an array",num10)
c=np.bincount(num10)
max1=c.argmax()
print("the most frequent value in an array is:\n",max1)

Entered values in an array [ 1  2  3  4 10  6  2  7  0  8]
the most frequent value in an array is:
 2


# 14.How to get the n largest values of an array

In [14]:
num11=np.arange(40)
print(num11)
print("\n",np.sort(num11))
c=num11[-1]
print("\n The largest values of an array:---->",c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]

 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]

 The largest values of an array:----> 39
